// Package contracts는 이더리움 스마트 컨트랙트와 상호작용하기 위한 ABI 바인딩을 제공합니다.
// Package contracts provides ABI bindings for interacting with Ethereum smart contracts.
package contracts

import (
	"math/big"

	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/ethclient"
)

// Aave V3 메인넷 컨트랙트 주소 / Aave V3 mainnet contract addresses
var (
	// AaveV3Pool은 Aave V3 Pool 프록시 주소입니다 (이더리움 메인넷).
	// AaveV3Pool is the Aave V3 Pool proxy address (Ethereum mainnet).
	AaveV3Pool = common.HexToAddress("0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2")

	// AaveV3Oracle은 Aave V3 Oracle 주소입니다.
	// AaveV3Oracle is the Aave V3 Oracle address.
	AaveV3Oracle = common.HexToAddress("0x54586bE62E3c3580375aE3723C145253060Ca0C2")
)

// UserAccountData는 Aave V3 Pool.getUserAccountData()의 반환값입니다.
// UserAccountData represents the return value of Aave V3 Pool.getUserAccountData().
type UserAccountData struct {
	// TotalCollateralBase는 총 담보 가치 (기본 통화 단위, 8 소수점).
	// TotalCollateralBase is total collateral value in base currency (8 decimals).
	TotalCollateralBase *big.Int

	// TotalDebtBase는 총 부채 가치 (기본 통화 단위, 8 소수점).
	// TotalDebtBase is total debt value in base currency (8 decimals).
	TotalDebtBase *big.Int

	// AvailableBorrowsBase는 추가 대출 가능 금액.
	// AvailableBorrowsBase is available borrows amount.
	AvailableBorrowsBase *big.Int

	// CurrentLiquidationThreshold는 현재 청산 기준 (10000 = 100%).
	// CurrentLiquidationThreshold is current liquidation threshold (10000 = 100%).
	CurrentLiquidationThreshold *big.Int

	// Ltv는 담보 대비 대출 비율 (10000 = 100%).
	// Ltv is loan-to-value ratio (10000 = 100%).
	Ltv *big.Int

	// HealthFactor는 헬스팩터 (1e18 = 1.0, < 1e18이면 청산 가능).
	// HealthFactor is health factor (1e18 = 1.0, < 1e18 = liquidatable).
	HealthFactor *big.Int
}

// AavePoolCaller는 Aave V3 Pool 컨트랙트를 호출하는 클라이언트입니다.
// AavePoolCaller is a client for calling the Aave V3 Pool contract.
type AavePoolCaller struct {
	client  *ethclient.Client
	address common.Address
}

// NewAavePoolCaller는 새로운 AavePoolCaller를 생성합니다.
// NewAavePoolCaller creates a new AavePoolCaller.
func NewAavePoolCaller(client *ethclient.Client, poolAddress common.Address) *AavePoolCaller {
	return &AavePoolCaller{
		client:  client,
		address: poolAddress,
	}
}

// GetUserAccountData는 사용자의 계정 데이터를 조회합니다.
// GetUserAccountData retrieves user's account data from Aave V3 Pool.
//
// 반환되는 데이터:
// - 총 담보 가치 (USD, 8 소수점)
// - 총 부채 가치 (USD, 8 소수점)
// - 추가 대출 가능 금액
// - 청산 기준
// - LTV
// - 헬스팩터 (1e18 스케일)
//
// Returns:
// - Total collateral value (USD, 8 decimals)
// - Total debt value (USD, 8 decimals)
// - Available borrows
// - Liquidation threshold
// - LTV
// - Health factor (1e18 scale)
func (c *AavePoolCaller) GetUserAccountData(opts *bind.CallOpts, user common.Address) (*UserAccountData, error) {
	// getUserAccountData(address) ABI 인코딩
	// Encode getUserAccountData(address) ABI
	//
	// 참고: 실제 구현에서는 abigen으로 생성된 바인딩을 사용합니다.
	// Note: In production, use bindings generated by abigen.
	//
	// 함수 시그니처: getUserAccountData(address)
	// Function signature: getUserAccountData(address)
	// 셀렉터: 0xbf92857c
	// Selector: 0xbf92857c

	// TODO: go-ethereum의 abi 패키지를 사용하여 실제 호출 구현
	// TODO: Implement actual call using go-ethereum's abi package
	//
	// 예시 코드 (abigen 바인딩 사용 시):
	// Example code (with abigen bindings):
	//
	// pool, err := aavev3.NewPool(c.address, c.client)
	// if err != nil {
	//     return nil, err
	// }
	// data, err := pool.GetUserAccountData(opts, user)
	// if err != nil {
	//     return nil, err
	// }

	_ = opts // suppress unused warning
	_ = user

	return &UserAccountData{}, nil
}

// ChainlinkRoundData는 Chainlink 가격 피드의 라운드 데이터입니다.
// ChainlinkRoundData represents round data from a Chainlink price feed.
type ChainlinkRoundData struct {
	// RoundId는 라운드 ID입니다.
	// RoundId is the round ID.
	RoundId *big.Int

	// Answer는 가격입니다 (일반적으로 8 소수점).
	// Answer is the price (typically 8 decimals).
	Answer *big.Int

	// StartedAt은 라운드 시작 시간입니다.
	// StartedAt is when the round started.
	StartedAt *big.Int

	// UpdatedAt은 마지막 업데이트 시간입니다 (지연 확인에 중요).
	// UpdatedAt is when the round was last updated (critical for staleness check).
	UpdatedAt *big.Int

	// AnsweredInRound는 답변이 계산된 라운드입니다.
	// AnsweredInRound is the round in which the answer was computed.
	AnsweredInRound *big.Int
}
